export const regions = [
  'IIV Markaziy apparati',
  'IIV JIED',
  'IIV TvaTOXTD',
  'IIV Akademiyasi',
  'IIV MOI',
  'QR IIV',
  'Andijon viloyati IIB',
  'Buxoro viloyati IIB',
  'Jizzax viloyati IIB',
  'Qashqadaryo viloyati IIB',
  'Navoiy viloyati IIB',
  'Namangan viloyati IIB',
  'Samarqand viloyati IIB',
  'Sirdaryo viloyati IIB',
  'Surxondaryo viloyati IIB',
  'Toshkent shahar IIBB',
  'Toshkent viloyati IIBB',
  'Fargʻona viloyati IIB',
  'Xorazm viloyati IIB',
  'IIV Harbiy tuzilmalar',
]
